#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Please specify filename without filetype"
    exit 1
fi

engine=pdflatex
bibengine=bibtex
skip_bib=0

for arg in "$@"; do
    case "$arg" in
    --skip-bib)
        skip_bib=1
        ;;
    --engine=*)
        engine="${arg#*=}"
        ;;
    --bibengine=*)
        bibengine="${arg#*=}"
        ;;
    esac
done

case "$engine" in
pdfTeX|pdflatex)
    engine="pdflatex --shell-escape"
    ;;
XeTeX|xelatex)
    engine="xelatex --shell-escape"
    ;;
LuaTeX|lualatex)
    engine="lualatex --shell-escape"
    ;;
*)
    echo "Invalid engine specified. Use one of: pdfTeX, XeTeX, LuaTeX"
    exit 2
    ;;
esac

$engine $1.tex

# Run the bibliography engine if not skipped
if [ "$skip_bib" -eq 0 ]; then
    case "$bibengine" in
    bibtex)
        bibtex $1
        ;;
    biber)
        biber $1
        ;;
    *)
        echo "Invalid bibliography engine specified. Use bibtex or biber."
        exit 3
        ;;
    esac
    # Second LaTeX run
    $engine $1.tex
fi

$engine $1.tex
